# Generated by Django 5.0.3 on 2024-04-26 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('hId', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('Ssofa', models.IntegerField(max_length=1)),
                ('tv', models.IntegerField(max_length=1)),
                ('wash_machine', models.IntegerField(max_length=1)),
                ('wifi', models.IntegerField(max_length=1)),
                ('bed', models.IntegerField(max_length=1)),
                ('refrigerator', models.IntegerField(max_length=1)),
                ('hotwater', models.IntegerField(max_length=1)),
                ('channel4', models.IntegerField(max_length=1)),
                ('cabinet', models.IntegerField(max_length=1)),
                ('aircond', models.IntegerField(max_length=1)),
                ('gas', models.IntegerField(max_length=1)),
            ],
            options={
                'db_table': 'Equipment',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('mId', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('gender', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('pId', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'Member',
            },
        ),
    ]
