# Generated by Django 5.0.3 on 2024-04-26 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipment',
            old_name='Ssofa',
            new_name='sofa',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='aircond',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='bed',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='cabinet',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='channel4',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='gas',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='hotwater',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='refrigerator',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='tv',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='wash_machine',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='wifi',
        ),
    ]
