# Generated by Django 5.0.3 on 2024-04-26 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_rename_ssofa_equipment_sofa_remove_equipment_aircond_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='aircond',
            field=models.IntegerField(default=0, max_length=1),
        ),
        migrations.AddField(
            model_name='equipment',
            name='bed',
            field=models.IntegerField(default=0, max_length=1),
        ),
        migrations.AddField(
            model_name='equipment',
            name='cabinet',
            field=models.IntegerField(default=0, max_length=1),
        ),
        migrations.AddField(
            model_name='equipment',
            name='channel4',
            field=models.IntegerField(default=0, max_length=1),
        ),
        migrations.AddField(
            model_name='equipment',
            name='gas',
            field=models.IntegerField(default=0, max_length=1),
        ),
        migrations.AddField(
            model_name='equipment',
            name='hotwater',
            field=models.IntegerField(default=0, max_length=1),
        ),
        migrations.AddField(
            model_name='equipment',
            name='refrigerator',
            field=models.IntegerField(default=0, max_length=1),
        ),
        migrations.AddField(
            model_name='equipment',
            name='tv',
            field=models.IntegerField(default=0, max_length=1),
        ),
        migrations.AddField(
            model_name='equipment',
            name='wash_machine',
            field=models.IntegerField(default=0, max_length=1),
        ),
        migrations.AddField(
            model_name='equipment',
            name='wifi',
            field=models.IntegerField(default=0, max_length=1),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='sofa',
            field=models.IntegerField(default=0, max_length=1),
        ),
    ]
