# Generated by Django 5.0.3 on 2024-04-26 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_equipment_aircond_equipment_bed_equipment_cabinet_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment2',
            fields=[
                ('hId', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('sofa', models.IntegerField(default=0, max_length=1)),
            ],
            options={
                'db_table': 'Equipment2',
            },
        ),
    ]
