# Generated by Django 5.0.3 on 2024-04-26 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_equipment2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Equipment2',
        ),
    ]
