# Generated by Django 5.0.3 on 2024-04-26 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_delete_equipment2'),
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('hId', models.CharField(default='TW', max_length=100, primary_key=True, serialize=False, unique=True)),
                ('status', models.IntegerField(default=0)),
                ('title', models.CharField(max_length=1000)),
                ('region', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'House',
            },
        ),
        migrations.AlterField(
            model_name='equipment',
            name='aircond',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='bed',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='cabinet',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='channel4',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='gas',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='hotwater',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='refrigerator',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='sofa',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='tv',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='wash_machine',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='wifi',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='hId',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='my_app.house'),
        ),
    ]
