# Generated by Django 5.0.3 on 2024-04-26 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0006_house_alter_equipment_aircond_alter_equipment_bed_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Equipment',
        ),

    ]
