# Generated by Django 5.0.3 on 2024-04-26 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0007_rename_gas_equipment_gass'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('hId', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='my_app.house')),
                ('sofa', models.IntegerField(default=0)),
                ('tv', models.IntegerField(default=0)),
                ('wash_machine', models.IntegerField(default=0)),
                ('wifi', models.IntegerField(default=0)),
                ('bed', models.IntegerField(default=0)),
                ('refrigerator', models.IntegerField(default=0)),
                ('hotwater', models.IntegerField(default=0)),
                ('channel4', models.IntegerField(default=0)),
                ('cabinet', models.IntegerField(default=0)),
                ('aircond', models.IntegerField(default=0)),
                ('gass', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'Equipment',
            },
        ),
    ]
