# Generated by Django 5.0.3 on 2024-04-26 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0008_equipment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipment',
            old_name='gass',
            new_name='gas',
        ),
    ]
