# Generated by Django 5.0.3 on 2024-04-26 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0009_rename_gass_equipment_gas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipment',
            old_name='hId',
            new_name='hhId',
        ),
    ]
