# Generated by Django 5.0.3 on 2024-04-26 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0010_rename_hid_equipment_hhid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipment',
            old_name='hhId',
            new_name='hId',
        ),
    ]
