# Generated by Django 5.0.3 on 2024-04-26 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0011_rename_hhid_equipment_hid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('hId', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='my_app.house')),
                ('price', models.IntegerField(default=0)),
                ('size', models.IntegerField(default=5)),
                ('address', models.CharField(default='--', max_length=1000, unique=True)),
                ('level', models.IntegerField(default=5)),
                ('room', models.IntegerField(default=1)),
                ('living', models.IntegerField(default=1)),
                ('bath', models.IntegerField(default=1)),
                ('type', models.CharField(default='--', max_length=10, unique=True)),
            ],
            options={
                'db_table': 'Info',
            },
        ),
    ]
