# Generated by Django 5.0.3 on 2024-04-26 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0012_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='type',
            field=models.CharField(default='--', max_length=10),
        ),
    ]
