# Generated by Django 5.0.3 on 2024-04-27 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0014_alter_info_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('path', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('hId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.house')),
            ],
            options={
                'db_table': 'Image',
            },
        ),
    ]
