# Generated by Django 5.0.3 on 2024-04-27 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0015_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rdetail',
            fields=[
                ('hId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='my_app.house')),
                ('status', models.IntegerField(default=0)),
                ('parking', models.CharField(default='無', max_length=20)),
                ('pet', models.IntegerField(default=0)),
                ('cook', models.IntegerField(default=0)),
                ('direction', models.CharField(default='--', max_length=10)),
                ('in_level', models.IntegerField(default=1)),
                ('age', models.IntegerField(default=0)),
                ('security', models.CharField(default='--', max_length=10)),
                ('management', models.IntegerField(default=0)),
                ('period', models.CharField(default='--', max_length=10)),
                ('bus', models.IntegerField(default=0)),
                ('train', models.IntegerField(default=0)),
                ('mrt', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'Rdetail',
            },
        ),
    ]
