# Generated by Django 5.0.3 on 2024-04-27 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0016_rdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='hId',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='my_app.house'),
        ),
    ]
