# Generated by Django 5.0.3 on 2024-04-27 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0018_alter_equipment_hid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userssss',
            fields=[
                ('mId', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(default='0', max_length=100)),
            ],
            options={
                'db_table': 'Userssss',
            },
        ),
    ]
