# Generated by Django 5.0.3 on 2024-04-28 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0019_userssss'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='size',
            field=models.FloatField(default=5),
        ),
        migrations.AlterField(
            model_name='rdetail',
            name='age',
            field=models.FloatField(default=0),
        ),
    ]
