# Generated by Django 5.0.3 on 2024-04-28 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0020_alter_info_size_alter_rdetail_age'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipment',
            old_name='wash_machine',
            new_name='washer',
        ),
    ]
