# Generated by Django 5.0.3 on 2024-04-28 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0021_rename_wash_machine_equipment_washer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipment',
            old_name='hotwater',
            new_name='heater',
        ),
    ]
