# Generated by Django 5.0.3 on 2024-04-28 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0022_rename_hotwater_equipment_heater'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rdetail',
            old_name='in_level',
            new_name='level',
        ),
    ]
