# Generated by Django 5.0.3 on 2024-04-29 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0024_usersssssssss'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersssssssss',
            old_name='id',
            new_name='iddddddd',
        ),
    ]
