# Generated by Django 5.0.3 on 2024-04-29 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0025_rename_id_usersssssssss_iddddddd'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usersssssssss',
        ),
    ]
